# Generated by Django 3.2.3 on 2021-05-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bearer', '0002_auto_20210520_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bearer_in',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bearer_out',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
