# Generated by Django 3.1.5 on 2021-05-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('heure', models.CharField(max_length=100)),
                ('Total_Transactions', models.PositiveIntegerField()),
                ('EFF', models.PositiveIntegerField()),
            ],
        ),
    ]
