# Generated by Django 3.2.3 on 2021-05-31 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalP', '0002_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='params',
            name='EFF',
            field=models.FloatField(),
        ),
    ]
