# Generated by Django 3.2.3 on 2021-06-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalP', '0003_alter_params_eff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='params',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
