# Generated by Django 3.1.5 on 2021-05-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdp', '0002_auto_20210301_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdp_in',
            name='date_mns',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pdp_out',
            name='date_mns',
            field=models.BigIntegerField(default=None),
        ),
    ]
